### ISSUE TITLE
Image Upload without S3 ?

### ISSUE THREAD

**Issue by daslicht** [greenlizard/hoodie-plugin-image#2]
Hi,
is it possible to upload images without the need for  S3 ?

~ Marc

**Comment by gabrielmancini** [comment]
hello Marc,

have u succed upload image?

**Comment by daslicht** [comment]
no not tried it yet with hoodie-plugin-image, but i saw that there is another plug which seam to allow upload to my own server , not tried it either tho.

Thank you !
